t ='hoehen'
def test(t):
        if any(w in t for w in ["baugesuch", "baubewilligung"]): return "objekte/baugesuche"
        elif any(w in t for w in ["grundbuch", "kataster", "parzelle", "vermess"]): return "objekte/grundbuchplan"
        elif any(w in t for w in ["baugrund", "untergrund", "geologie"]): return "baugrundklassen/"
        elif any(w in t for w in ["altlast", "bodenbelast"]): return "bodenbelastung/altlasten"
        elif "bodenverschieb" in t: return "bodenbelastung/bodenverschiebungen"
        elif any(w in t for w in ["bistum", "kirche", "pfarrei"]): return "bistum/"
        elif any(w in t for w in ["bodenkarte", "pedolog", "boden " ]): return "boden/karten"
        elif any(w in t for w in ["melioration", "bodenverbesserung", "boden verbesserung"]): return "boden/verbesserungen"
        elif "kartier" in t: return "boden/kartierung"
        elif "bage" in t: return "bage"
        elif any(w in t for w in ["geak", "gebaeudeenergie geak"]): return "gebaeudeenergie/geak"
        elif any(w in t for w in ["heizung", "wärme", "waerme", "heiz"]): return "gebaeudeenergie/heizungen"
        elif any(w in t for w in ["solar", "photovoltaik", "pv"]): return "gebaeudeenergie/solarpotential"
        elif any(w in t for w in ["erdwärme", "erdwaerme", "tiefenwärme"]): return "gebaeudeenergie/erdwaerme"
        elif any(w in t for w in ["energieplanung", "energiestadt"]): return "energieplanung/planung"
        elif "energiestadt" in t: return "energieplanung/energiestadt"
        elif "fischerei" in t: return "fauna/fischerei"
        elif "jagd" in t: return "fauna/jagd"
        elif any(w in t for w in ["hundeleinenpflicht", "leinenpflicht"]): return "fauna/hundeleinenpflicht"
        elif "fff" in t: return "fff"
        elif any(w in t for w in ["mobilfunk", "antenne", "sender"]): return "infrastruktur/mobilfunk"
        elif any(w in t for w in ["strassenbeleuchtung", "straßenbeleuchtung", "beleuchtung"]): return "infrastruktur/strassenbeleuchtung"
        elif "2017" in t and "histor" in t: return "historische_karten/2017"
        elif "1970" in t and "histor" in t: return "historische_karten/1970"
        elif "1930" in t and "histor" in t: return "historische_karten/1930"
        elif any(w in t for w in ["1880", "siegfried", "dufour"]): return "historische_karten/1880"
        elif any(w in t for w in ["1864", "1867"]) and "histor" in t: return "historische_karten/1864-1867"
        elif any(w in t for w in ["klimaanalyse", "heiß", "heiss", "hitze", "hitzetag"]): return "klimakarten/klimaanalyse_tag"
        elif any(w in t for w in ["klimaanalyse nacht", "nachtkühl", "nachtkuehl"]): return "klimakarten/klimaanalyse_nacht"
        elif "planungshinweis" in t and "tag" in t: return "klimakarten/planungshinweise_tag"
        elif "planungshinweis" in t and "nacht" in t: return "klimakarten/planungshinweise_nacht"
        elif any(w in t for w in ["denkmal", "schutzobjekt", "inventar kulturgüter", "kulturgüter", "kulturgueter"]): return "kulturgueter/denkmaeler"
        elif any(w in t for w in ["fundstelle", "archäologie", "archaeologie"]): return "kulturgueter/fundstellen"
        elif "isos" in t: return "kulturgueter/isos"
        elif any(w in t for w in ["lärm strasse", "laerm strasse", "strassenlaerm", "verkehrslaerm"]): return "laerm/strassenlaerm"
        elif any(w in t for w in ["schiesslärm", "schiesslaerm", "schiess"]): return "laerm/schiesslaerm"
        elif any(w in t for w in ["landwert zone", "bodenrichtwert zone", "zonenwert"]): return "landwerte/zone"
        elif any(w in t for w in ["landwert efh", "einfamilienhaus"]): return "landwerte/efh"
        elif "stockwerkeigentum" in t: return "landwerte/stockwerkeigentum"
        elif "gewerbe" in t and "landwert" in t: return "landwerte/gewerbe"
        elif any(w in t for w in ["bff ", "biodiversitätsförder", "biodiversitaetsfoerder"]): return "landwirtschaft/bff"
        elif any(w in t for w in ["ln ", "landwirtschaftliche nutzfl", "landwirtschaftliche nutzflaechen"]): return "landwirtschaft/ln"
        elif "bewirtschaftung" in t: return "landwirtschaft/bewirtschaftung"
        elif "pflanzenschutz" in t: return "landwirtschaft/pflanzenschutz"
        elif "bodenschutz" in t: return "landwirtschaft/bodenschutz"
        elif "grundlagen" in t and "landwirtschaft" in t: return "landwirtschaft/grundlagen"
        elif "luft" == t or any(w in t for w in ["luftqualität", "luftqualitaet", "immission"]): return "luft"
        elif any(w in t for w in ["sommertage"]): return "klimaszenarien/sommertage"
        elif any(w in t for w in ["hitzetage"]): return "klimaszenarien/hitzetage"
        elif any(w in t for w in ["tropennächte", "tropennaechte"]): return "klimaszenarien/tropennaechte"
        elif "frosttage" in t: return "klimaszenarien/frosttage"
        elif "eistage" in t: return "klimaszenarien/eistage"
        elif "neuschneetage" in t: return "klimaszenarien/neuschneetage"
        elif any(w in t for w in ["niederschlag", "regen"]): return "klimaszenarien/niederschlag"
        elif any(w in t for w in ["tagesmitteltemperatur", "mitteltemperatur"]): return "klimaszenarien/tagesmitteltemperatur"
        elif "tagesmaximumtemperatur" in t: return "klimaszenarien/tagesmaximumtemperatur"
        elif "tagesminimumtemperatur" in t: return "klimaszenarien/tagesminimumtemperatur"
        elif "synopt" in t: return "naturrisiken/synoptisch"
        elif any(w in t for w in ["einzelprozess", "einzelprozesse"]): return "naturrisiken/einzelprozesse"
        elif any(w in t for w in ["bundesinventar", "inventar bundes"]): return "naturinventare/bundesinventare"
        elif "inr" in t: return "naturinventare/inr"
        elif any(w in t for w in ["bestandesaufnahme", "bestandesaufnahmen"]): return "naturinventare/bestandesaufnahmen"
        elif any(w in t for w in ["gefahrenkarte", "gefahrenkarte", "gefahr " , "naturgefahr"]): return "naturgefahren/gefahrenkarten"
        elif "intensitaet" in t or "intensität" in t: return "naturgefahren/intensitaet"
        elif any(w in t for w in ["fließ", "fliess", "fliesstiefe", "fließtiefe"]): return "naturgefahren/fliesstiefen"
        elif any(w in t for w in ["oberflächenabfluss", "oberflaechenabfluss"]): return "naturgefahren/oberflaechenabfluss"
        elif "baulinie" in t: return "nutzungsplanung/baulinien"
        elif "planungszone" in t: return "nutzungsplanung/planungszonen"
        elif any(w in t for w in ["sondernutzung", "sondernutzungsplan"]): return "nutzungsplanung/sondernutzung"
        elif any(w in t for w in ["gewaesserraum", "gewässerraum"]): return "nutzungsplanung/gewaesserraum"
        elif any(w in t for w in ["gefahrenzone", "gefahrenzonen"]): return "nutzungsplanung/gefahrenzonen"
        elif any(w in t for w in ["lärmempfind", "laermempfind"]): return "nutzungsplanung/laermempfindlichkeit"
        elif any(w in t for w in ["zonenplan", "nutzungsplan"]): return "nutzungsplanung/zonenplan"
        elif any(w in t for w in ["luftbild", "orthofoto", "orthophoto", "aerophoto", "luftaufnahme"]): return "luftbilder/2023"
        elif any(w in t for w in ["luftbild 2020", "orthofoto 2020"]): return "luftbilder/2020"
        elif any(w in t for w in ["luftbild 2017", "orthofoto 2017"]): return "luftbilder/2017"
        elif any(w in t for w in ["luftbild 2014", "orthofoto 2014"]): return "luftbilder/2014"
        elif any(w in t for w in ["luftbild 2011", "orthofoto 2011"]): return "luftbilder/2011"
        elif any(w in t for w in ["luftbild 2008", "orthofoto 2008"]): return "luftbilder/2008"
        elif any(w in t for w in ["luftbild 2005", "orthofoto 2005"]): return "luftbilder/2005"
        elif any(w in t for w in ["luftbild 1998", "orthofoto 1998"]): return "luftbilder/1998"
        elif "ortsplan" in t: return "ortsplan"
        elif any(w in t for w in ["technische gefahr", "störfall", "stoerfall"]): return "technische_gefahren/"
        elif "wanderweg" in t and "teilrichtplan" in t: return "teilrichtplan/wanderwege"
        elif "siedlungslenkung" in t: return "teilrichtplan/siedlungslenkung"
        elif any(w in t for w in ["regionale entwicklungsträger", "regionale entwicklungstraeger"]): return "teilrichtplan/regionale_entwicklungstraeger"
        elif any(w in t for w in ["gewässer", "gewaesser", "wasser", "see", "fluss", "bach"]): return "oberflaechengewaesser/netz"
        elif "oekomorphologie" in t and "oberflaechengewaesser" in t: return "oberflaechengewaesser/oekomorphologie"
        elif "revitalisier" in t and "oberflaechengewaesser" in t: return "oberflaechengewaesser/revitalisierung"
        elif "sanierung wasserkraft" in t or "wasserkraft sanierung" in t: return "sanierung_wasserkraft/"
        elif "schutzbauten" in t and "bevoelkerungsschutz" not in t: return "schutzbauten"
        elif "schutzverordnung" in t or "schutzverordnungen" in t: return "schutzverordnungen"
        elif "bevoelkerungsschutz" in t and "schutzbauten" in t: return "bevoelkerungsschutz/schutzbauten"
        elif "alarmierung" in t: return "bevoelkerungsschutz/alarmierung"
        elif "notfalltreffpunkt" in t or "notfall-treffpunkt" in t: return "bevoelkerungsschutz/notfalltreffpunkte"
        elif any(w in t for w in ["sportanlage", "sport anlage", "sporthalle", "sportplatz"]): return "sport/anlagen"
        elif "namenbuch" in t: return "namenbuch/"
        elif any(w in t for w in ["strassennetz", "verkehrsnetz", "strassen netz"]): return "strassen/netz"
        elif "ausnahmetransportroute" in t: return "strassen/ausnahmetransportrouten"
        elif any(w in t for w in ["verkehrszählung", "verkehrszaehlung"]): return "strassen/verkehrszaehlung"
        elif any(w in t for w in ["öpnv", "oev", "oepnv", "bus", "bahn", "zug"]): return "oev/netz"
        elif "angebotsstufe" in t: return "oev/angebotsstufen"
        elif "einzugsgebiet" in t: return "oev/einzugsgebiete"
        elif "wanderwege" in t and "oev" in t: return "oev/wanderwege"
        elif "uebersichtsplan" in t or "übersichtsplan" in t: return "uebersichtsplan"
        elif "standortsuche" in t: return "standortsuche"
        elif any(w in t for w in ["vierwaldst", "vierwaldstaetter", "vierwaldstätter"]): return "vierwaldstaettersee/schutz_und_nutzung"
        elif "wasserpflanzen" in t: return "vierwaldstaettersee/wasserpflanzen"
        elif "oekomorphologie" in t and "vierwaldstaettersee" in t: return "vierwaldstaettersee/oekomorphologie"
        elif "revitalisierungsplanung" in t: return "vierwaldstaettersee/revitalisierungsplanung"
        elif "waldstandort" in t: return "wald/standorte"
        elif "waldbestand" in t or ("wald" in t and "bestand" in t): return "wald/bestand"
        elif "waldfunktion" in t or ("wald" in t and "funktion" in t): return "wald/funktionen"
        elif "waldstrasse" in t or ("wald" in t and "strasse" in t): return "wald/strassen"
        elif "waldbrand" in t: return "wald/waldbrand"
        elif "vernetzung ist" in t: return "vernetzung/ist"
        elif "vernetzung soll" in t: return "vernetzung/soll"
        elif "grundwasser schutz" in t or ("grundwasser" in t and "schutz" in t): return "grundwasser/schutz"
        elif "grundwasser vorkommen" in t or ("grundwasser" in t and "vorkommen" in t): return "grundwasser/vorkommen"
        elif any(w in t for w in ["höhe", "hoehe","hoehen" "terrain", "dtm", "dom"]): return "hoehen"
        else: return "objekte/grundbuchplan"
print(test('hoehen'))